import { AnyReport, ReportAssignment, Announcement, GeneratedReport } from "@/lib/types";
import { generateMockReports } from "./data_factory";


// Mock Reports
export const MOCK_REPORTS: AnyReport[] = [
  ...generateMockReports({ count: 105 }),
];

export const MOCK_ASSIGNMENTS: ReportAssignment[] = [
  {
    assignmentId: "assign-1",
    reportId: "rep-2",
    accountId: "staff-1",
    assignedAt: "2023-10-25T09:00:00Z",
    actionTaken: "Technician notified.",
  },
];

// Mock Announcements
export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    announcementId: "ann-1",
    title: "Campus Safety Week 2023",
    message: "Join us for Campus Safety Week from November 1-7. Various activities and workshops on personal safety, crime prevention, and emergency preparedness will be conducted. All students and staff are encouraged to participate.",
    audience: "ALL",
    type: "EVENT",
    status: "PUBLISHED",
    priority: "HIGH",

    startDate: "2023-11-01T00:00:00Z",
    endDate: "2023-11-07T23:59:59Z",
    createdAt: "2023-10-20T10:00:00Z",
    createdBy: "staff-1",
   
    updatedAt: "2023-10-20T10:00:00Z",
  },
  {
    announcementId: "ann-2",
    title: "Emergency Maintenance - Block C",
    message: "Emergency maintenance work will be carried out in Block C on October 30, 2023, from 9:00 AM to 5:00 PM. Water and electricity supply will be temporarily interrupted. Please plan accordingly.",
    audience: "ALL",
    type: "EMERGENCY",
    status: "PUBLISHED",
    priority: "HIGH",
 
    startDate: "2025-12-01T00:00:00Z",
    endDate: "2025-12-30T23:59:59Z",
    createdAt: "2023-10-27T14:30:00Z",
    createdBy: "staff-1",
    
    updatedAt: "2023-10-27T14:30:00Z",
  },
  {
    announcementId: "ann-3",
    title: "New Crime Reporting Portal",
    message: "We are pleased to announce the launch of our new online crime reporting portal. Students and staff can now submit reports 24/7 through this platform. Visit the Crime Terminal section to get started.",
    audience: "ALL",
    type: "GENERAL",
    status: "PUBLISHED",
    priority: "MEDIUM",
    
    startDate: "2025-12-01T00:00:00Z",
    endDate: "2025-12-30T23:59:59Z",
    createdAt: "2023-10-15T09:00:00Z",
    createdBy: "staff-1",
    
    updatedAt: "2023-10-15T09:00:00Z",
  },
  {
    announcementId: "ann-4",
    title: "Updated Emergency Contact Numbers",
    message: "Please note that the UiTM Auxiliary Police emergency contact numbers have been updated. The new hotline is 03-5544-2222. Please update your contact lists accordingly.",
    audience: "ALL",
    type: "GENERAL",
    status: "PUBLISHED",
    priority: "MEDIUM",
    
    startDate: "2023-10-10T00:00:00Z",
    endDate: "2023-11-30T23:59:59Z",
    createdAt: "2023-10-10T11:00:00Z",
    createdBy: "staff-1",
    
    updatedAt: "2023-10-10T11:00:00Z",
  },
  {
    announcementId: "ann-5",
    title: "Staff Training: Report Management",
    message: "Mandatory training session for all staff members on the new report management system. Session will be held on November 5, 2023, at 2:00 PM in Meeting Room A.",
    audience: "STAFF",
    type: "EVENT",
    status: "PUBLISHED",
    priority: "HIGH",
    
    startDate: "2023-10-25T00:00:00Z",
    endDate: "2023-11-05T23:59:59Z",
    createdAt: "2023-10-25T08:00:00Z",
    createdBy: "staff-1",
    
    updatedAt: "2023-10-25T08:00:00Z",
  },
  {
    announcementId: "ann-6",
    title: "Draft: Upcoming Security Policy Changes",
    message: "This is a draft announcement about upcoming changes to campus security policies. Will be published after review.",
    audience: "ALL",
    type: "GENERAL",
    status: "DRAFT",
    priority: "LOW",
    
    startDate: "2023-11-15T00:00:00Z",
    endDate: "2023-12-31T23:59:59Z",
    createdAt: "2023-10-26T15:00:00Z",
    createdBy: "staff-1",
    
    updatedAt: "2023-10-26T15:00:00Z",
  },
];

// Mock Generated Reports
export const MOCK_GENERATED_REPORTS: GeneratedReport[] = [
  {
    generateId: "gen-rep-1",
    generatedBy: "staff-1",
    title: "Monthly Crime Report - October 2023",
    summary: "Comprehensive analysis of crime reports submitted during October 2023. This report includes statistics on crime categories, resolution rates, and location hotspots.",
    dateRangeStart: "2023-10-01T00:00:00Z",
    dateRangeEnd: "2023-10-31T23:59:59Z",
    reportCategory: "CRIME",
    reportDataType: "DETAILED",
    requestedAt: "2023-11-01T09:00:00Z",
    reportData: {
      totalReports: 15,
      pendingReports: 3,
      resolvedReports: 10,
      inProgressReports: 2,
      crimeReports: 15,
      facilityReports: 0,
      executiveSummary: "October 2023 recorded 15 crime incidents across campus with an overall resolution rate of 67%. Theft remains the primary concern, accounting for 53% of all reported cases. Most incidents occurred in high-traffic areas during peak hours.",
      keyStatistics: {
        totalIncidents: 15,
        byStatus: {
          pending: 3,
          inProgress: 2,
          resolved: 10,
          rejected: 0,
        },
      },
      detailedAnalysis: "The theft incidents primarily involved unattended personal belongings in public areas. PTAR Library showed highest concentration with 5 cases, followed by the Cafeteria with 3 cases. Two assault cases required immediate security intervention, while vandalism incidents targeted public property in parking areas.",
      topLocations: [
        { location: "PTAR Library", count: 5 },
        { location: "Cafeteria", count: 3 },
        { location: "Sports Complex", count: 3 },
        { location: "Parking Lot A", count: 2 },
        { location: "Block C", count: 2 },
      ],
      riskAssessment: {
        level: "MEDIUM",
        factors: [
          "High concentration of incidents in library area",
          "Unattended belongings in public spaces",
          "Limited surveillance in parking areas",
          "Peak hour vulnerabilities",
        ],
      },
      recommendations: [
        "Increase security patrols in PTAR Library and cafeteria areas",
        "Install additional CCTV cameras in parking lots",
        "Launch awareness campaign on personal property security",
        "Improve lighting in outdoor areas",
        "Establish security checkpoints during peak hours",
      ],
      conclusion: "While the October crime rate remains manageable, concentrated efforts in high-risk areas will significantly enhance campus safety. Immediate focus on library and cafeteria security is recommended.",
      reportsByCategory: {
        THEFT: 8,
        ASSAULT: 2,
        VANDALISM: 3,
        HARASSMENT: 1,
        OTHER: 1,
      },
      reportsByStatus: {
        PENDING: 3,
        IN_PROGRESS: 2,
        RESOLVED: 10,
        REJECTED: 0,
      },
      reportsByMonth: [
        { month: "Oct 2023", count: 15 },
      ],
      averageResolutionTime: 3.5,
    },
  },
  {
    generateId: "gen-rep-2",
    generatedBy: "staff-1",
    title: "Facility Issues Summary - Q3 2023",
    summary: "Quarterly summary of facility issues reported across campus. Highlights maintenance priorities and recurring problems.",
    dateRangeStart: "2023-07-01T00:00:00Z",
    dateRangeEnd: "2023-09-30T23:59:59Z",
    reportCategory: "FACILITY",
    reportDataType: "SUMMARY",
    requestedAt: "2023-10-05T14:30:00Z",
    reportData: {
      totalReports: 42,
      pendingReports: 5,
      resolvedReports: 35,
      inProgressReports: 2,
      crimeReports: 0,
      facilityReports: 42,
      executiveSummary: "Q3 2023 facility maintenance summary reveals 42 reported issues with an 83% resolution rate. Electrical and plumbing systems require significant attention, particularly in older campus buildings. Overall maintenance response time averaged 2.1 days.",
      keyStatistics: {
        totalIncidents: 42,
        byStatus: {
          pending: 5,
          inProgress: 2,
          resolved: 35,
          rejected: 0,
        },
      },
      detailedAnalysis: "Electrical issues dominated the quarter with 15 cases (36%), primarily involving circuit failures and lighting problems. Plumbing concerns accounted for 12 cases (29%), mostly water leaks and drainage issues. August showed peak activity with 18 reports, likely due to heavy rainfall affecting infrastructure.",
      topLocations: [
        { location: "Hostel Block 1", count: 11 },
        { location: "Block A", count: 10 },
        { location: "Block C", count: 8 },
        { location: "Library", count: 7 },
        { location: "Cafeteria", count: 6 },
      ],
      riskAssessment: {
        level: "MEDIUM",
        factors: [
          "Aging electrical systems in older buildings",
          "Recurring plumbing issues indicate systemic problems",
          "Weather-related infrastructure vulnerabilities",
          "Furniture replacement needs in student areas",
        ],
      },
      recommendations: [
        "Schedule comprehensive electrical audit for Blocks A and C",
        "Implement preventive plumbing maintenance program",
        "Upgrade drainage systems in vulnerable areas",
        "Allocate budget for systematic furniture replacement",
        "Establish rapid response team for urgent repairs",
      ],
      conclusion: "The quarterly facility performance indicates need for proactive maintenance strategies. While resolution rates are satisfactory, addressing root causes will reduce recurring issues and improve campus infrastructure reliability.",
      reportsByCategory: {
        ELECTRICAL: 15,
        PLUMBING: 12,
        FURNITURE: 8,
        INFRASTRUCTURE: 5,
        OTHER: 2,
      },
      reportsByStatus: {
        PENDING: 5,
        IN_PROGRESS: 2,
        RESOLVED: 35,
        REJECTED: 0,
      },
      reportsByMonth: [
        { month: "Jul 2023", count: 12 },
        { month: "Aug 2023", count: 18 },
        { month: "Sep 2023", count: 12 },
      ],
      averageResolutionTime: 2.1,
    },
  },
  {
    generateId: "gen-rep-3",
    generatedBy: "staff-1",
    title: "Campus User Statistics - 2023",
    summary: "Annual overview of user statistics across the campus including students and staff activity.",
    dateRangeStart: "2023-01-01T00:00:00Z",
    dateRangeEnd: "2023-12-31T23:59:59Z",
    reportCategory: "USER",
    reportDataType: "DETAILED",
    requestedAt: "2023-11-15T10:00:00Z",
    reportData: {
      totalReports: 156,
      pendingReports: 12,
      resolvedReports: 130,
      inProgressReports: 14,
      crimeReports: 48,
      facilityReports: 108,
      executiveSummary: "The 2023 annual report documents 156 total incidents across campus, with facility issues (69%) significantly outnumbering security incidents (31%). Overall resolution rate of 83% demonstrates effective response systems, though facility maintenance requires enhanced attention.",
      keyStatistics: {
        totalIncidents: 156,
        byStatus: {
          pending: 12,
          inProgress: 14,
          resolved: 130,
          rejected: 0,
        },
      },
      detailedAnalysis: "Annual trends reveal clear seasonal patterns with incident peaks during academic semesters (March-May: 34 incidents, September-November: 53 incidents) and significant drops during breaks. PTAR Library emerged as the highest-activity location with 25 incidents. Facility issues concentrated in electrical (32%) and plumbing (26%) categories, suggesting infrastructure aging concerns.",
      topLocations: [
        { location: "PTAR Library", count: 25 },
        { location: "Block A", count: 20 },
        { location: "Cafeteria", count: 18 },
        { location: "Hostel Block 1", count: 15 },
        { location: "Parking Lot A", count: 12 },
      ],
      riskAssessment: {
        level: "MEDIUM",
        factors: [
          "Aging infrastructure requiring systematic upgrades",
          "Seasonal incident patterns correlating with academic calendar",
          "High-traffic areas showing elevated incident rates",
          "Growing facility maintenance backlog",
          "Limited resources during peak periods",
        ],
      },
      recommendations: [
        "Develop comprehensive infrastructure modernization plan",
        "Increase maintenance team capacity by 25%",
        "Implement predictive maintenance systems",
        "Enhance security presence in high-traffic locations",
        "Establish seasonal response protocols for peak periods",
        "Create dedicated budget for preventive maintenance",
        "Deploy smart monitoring systems in critical facilities",
      ],
      conclusion: "Campus operations in 2023 demonstrated resilience with strong resolution rates, but underlying infrastructure challenges require strategic long-term investment. Proactive maintenance and security enhancement will be essential for sustained campus safety and functionality.",
      reportsByCategory: {
        THEFT: 20,
        ASSAULT: 8,
        VANDALISM: 12,
        HARASSMENT: 5,
        OTHER: 3,
        ELECTRICAL: 35,
        PLUMBING: 28,
        FURNITURE: 25,
        INFRASTRUCTURE: 15,
      },
      reportsByStatus: {
        PENDING: 12,
        IN_PROGRESS: 14,
        RESOLVED: 130,
        REJECTED: 0,
      },
      reportsByMonth: [
        { month: "Jan", count: 10 },
        { month: "Feb", count: 12 },
        { month: "Mar", count: 15 },
        { month: "Apr", count: 11 },
        { month: "May", count: 8 },
        { month: "Jun", count: 5 },
        { month: "Jul", count: 12 },
        { month: "Aug", count: 18 },
        { month: "Sep", count: 14 },
        { month: "Oct", count: 22 },
        { month: "Nov", count: 17 },
        { month: "Dec", count: 12 },
      ],
      averageResolutionTime: 2.8,
    },
  },
  {
    generateId: "gen-rep-4",
    generatedBy: "staff-1",
    title: "Weekly Crime Report - Nov Week 4",
    summary: "Weekly summary of crime incidents for the last week of November 2023.",
    dateRangeStart: "2023-11-20T00:00:00Z",
    dateRangeEnd: "2023-11-26T23:59:59Z",
    reportCategory: "CRIME",
    reportDataType: "SUMMARY",
    requestedAt: "2023-11-27T08:00:00Z",
    reportData: {
      totalReports: 5,
      pendingReports: 1,
      resolvedReports: 3,
      inProgressReports: 1,
      crimeReports: 5,
      facilityReports: 0,
      executiveSummary: "During the week of November 20-26, 2023, a total of 5 crime incidents were reported across campus. The incidents primarily involved theft (3 cases) and vandalism (2 cases). Response time averaged 1.2 hours with 60% resolution rate.",
      keyStatistics: {
        totalIncidents: 5,
        byStatus: {
          pending: 1,
          inProgress: 1,
          resolved: 3,
          rejected: 0,
        },
      },
      detailedAnalysis: "The majority of incidents occurred during evening hours (6 PM - 10 PM), particularly in parking areas and near the library. Three theft cases involved unattended personal belongings, while two vandalism incidents targeted public property.",
      riskAssessment: {
        level: "MEDIUM",
        factors: [
          "Increased evening activity with limited lighting",
          "High foot traffic in library area",
          "Insufficient security patrol coverage",
        ],
      },
      recommendations: [
        "Increase security patrol frequency during evening hours",
        "Enhance lighting in parking areas",
        "Launch awareness campaign on personal belongings security",
        "Install additional CCTV cameras near hotspot locations",
      ],
      topLocations: [
        { location: "Parking Lot A", count: 2 },
        { location: "PTAR Library", count: 2 },
        { location: "Block C", count: 1 },
      ],
      conclusion: "The crime rate remains manageable but requires proactive measures to prevent escalation. Enhanced security presence and improved lighting are immediate priorities.",
    },
  },
  {
    generateId: "gen-rep-5",
    generatedBy: "staff-1",
    title: "Facility Maintenance Priority Report - December 2023",
    summary: "Priority assessment of facility issues requiring urgent attention across campus facilities.",
    dateRangeStart: "2023-12-01T00:00:00Z",
    dateRangeEnd: "2023-12-15T23:59:59Z",
    reportCategory: "FACILITY",
    reportDataType: "DETAILED",
    requestedAt: "2023-12-16T10:00:00Z",
    reportData: {
      totalReports: 28,
      pendingReports: 8,
      resolvedReports: 18,
      inProgressReports: 2,
      crimeReports: 0,
      facilityReports: 28,
      executiveSummary: "Analysis of 28 facility reports submitted in the first half of December 2023 reveals critical maintenance needs, particularly in electrical systems and plumbing infrastructure. Immediate action required for 8 high-priority cases.",
      keyStatistics: {
        totalIncidents: 28,
        byStatus: {
          pending: 8,
          inProgress: 2,
          resolved: 18,
          rejected: 0,
        },
      },
      detailedAnalysis: "Electrical issues constitute 43% of all reports, with most stemming from aging wiring systems in older campus buildings. Plumbing problems account for 32%, primarily water leaks and drainage issues. The average resolution time has increased to 3.5 days, exceeding the target of 2 days.",
      riskAssessment: {
        level: "HIGH",
        factors: [
          "Aging electrical infrastructure poses safety risks",
          "Multiple plumbing leaks causing water damage",
          "Delayed maintenance leading to escalated problems",
          "Limited maintenance staff during holiday period",
        ],
      },
      recommendations: [
        "Prioritize electrical system inspections in Buildings A, C, and E",
        "Schedule comprehensive plumbing assessment for all dormitories",
        "Increase maintenance team capacity during peak periods",
        "Implement predictive maintenance program",
        "Allocate emergency budget for critical repairs",
      ],
      topLocations: [
        { location: "Block A", count: 8 },
        { location: "Block C", count: 7 },
        { location: "Block E", count: 6 },
        { location: "Hostel Block 2", count: 4 },
        { location: "Cafeteria", count: 3 },
      ],
      conclusion: "The facility maintenance backlog requires immediate attention to prevent safety incidents and property damage. A systematic approach with prioritized action plan is essential.",
    },
  },
  {
    generateId: "gen-rep-6",
    generatedBy: "staff-1",
    title: "All Reports Overview - November 2023",
    summary: "Comprehensive overview of all reported incidents including crime and facility issues for November 2023.",
    dateRangeStart: "2023-11-01T00:00:00Z",
    dateRangeEnd: "2023-11-30T23:59:59Z",
    reportCategory: "ALL REPORTS",
    reportDataType: "SUMMARY",
    requestedAt: "2023-12-01T09:00:00Z",
    reportData: {
      totalReports: 43,
      pendingReports: 9,
      resolvedReports: 31,
      inProgressReports: 3,
      crimeReports: 17,
      facilityReports: 26,
      executiveSummary: "November 2023 witnessed a total of 43 incidents reported across campus, including 17 crime-related cases and 26 facility maintenance requests. Overall resolution rate stands at 72%, with average response time of 2.8 hours.",
      keyStatistics: {
        totalIncidents: 43,
        byStatus: {
          pending: 9,
          inProgress: 3,
          resolved: 31,
          rejected: 0,
        },
      },
      detailedAnalysis: "November data shows balanced distribution between crime (40%) and facility (60%) incidents. Peak reporting occurred mid-month coinciding with mid-semester examinations. Crime incidents primarily involved theft and vandalism, while facility reports centered on electrical and plumbing issues.",
      topLocations: [
        { location: "PTAR Library", count: 9 },
        { location: "Block A", count: 8 },
        { location: "Cafeteria", count: 7 },
        { location: "Parking Lot B", count: 6 },
        { location: "Hostel Block 1", count: 5 },
      ],
      riskAssessment: {
        level: "MEDIUM",
        factors: [
          "Mid-semester examination stress period",
          "Increased facility usage during peak academic activity",
          "Weather-related infrastructure challenges",
        ],
      },
      recommendations: [
        "Maintain heightened security during examination periods",
        "Schedule preventive maintenance before semester peaks",
        "Enhance communication channels for incident reporting",
      ],
      conclusion: "November performance metrics remain within acceptable ranges. Continued monitoring and proactive measures will ensure sustained campus safety and operational efficiency.",
    },
  },
  {
    generateId: "gen-rep-7",
    generatedBy: "staff-1",
    title: "Semester End Security Report - Dec 2023",
    summary: "Security and safety assessment for the end of semester period.",
    dateRangeStart: "2023-12-01T00:00:00Z",
    dateRangeEnd: "2023-12-20T23:59:59Z",
    reportCategory: "CRIME",
    reportDataType: "DETAILED",
    requestedAt: "2023-12-21T11:00:00Z",
    reportData: {
      totalReports: 22,
      pendingReports: 4,
      resolvedReports: 16,
      inProgressReports: 2,
      crimeReports: 22,
      facilityReports: 0,
      executiveSummary: "End-of-semester period analysis shows 22 security incidents with theft being the predominant concern (12 cases). Increased campus activity during examination period correlates with higher incident rates.",
      keyStatistics: {
        totalIncidents: 22,
        byStatus: {
          pending: 4,
          inProgress: 2,
          resolved: 16,
          rejected: 0,
        },
      },
      detailedAnalysis: "Examination stress period coincides with elevated theft incidents, particularly targeting electronic devices and personal belongings left unattended in study areas. Library and cafeteria remain high-risk zones.",
      riskAssessment: {
        level: "HIGH",
        factors: [
          "High student concentration in limited areas",
          "Extended library operating hours",
          "Increased stress levels affecting vigilance",
          "Opportunistic theft targeting exam materials",
        ],
      },
      recommendations: [
        "Deploy additional security personnel in library and study areas",
        "Install temporary surveillance in high-traffic zones",
        "Distribute security awareness reminders via student channels",
        "Implement locker system for personal belongings",
      ],
      topLocations: [
        { location: "PTAR Library", count: 8 },
        { location: "Cafeteria", count: 5 },
        { location: "Study Room Block B", count: 4 },
        { location: "Parking Lot A", count: 3 },
        { location: "Block C Corridor", count: 2 },
      ],
      conclusion: "Proactive security measures during examination periods are essential to maintain campus safety and student confidence.",
    },
  },
  {
    generateId: "gen-rep-8",
    generatedBy: "staff-1",
    title: "Annual Campus Safety Report 2023",
    summary: "Comprehensive annual report covering all safety and security aspects across campus for the year 2023.",
    dateRangeStart: "2023-01-01T00:00:00Z",
    dateRangeEnd: "2023-12-31T23:59:59Z",
    reportCategory: "ALL REPORTS",
    reportDataType: "DETAILED",
    requestedAt: "2024-01-05T09:00:00Z",
    reportData: {
      totalReports: 198,
      pendingReports: 15,
      resolvedReports: 175,
      inProgressReports: 8,
      crimeReports: 73,
      facilityReports: 125,
      executiveSummary: "The year 2023 recorded a total of 198 incidents across campus, comprising 73 crime reports and 125 facility maintenance requests. The data reveals a 12% decrease in crime incidents compared to 2022, while facility reports increased by 8%, indicating improved reporting culture.",
      keyStatistics: {
        totalIncidents: 198,
        byStatus: {
          pending: 15,
          inProgress: 8,
          resolved: 175,
          rejected: 0,
        },
      },
      detailedAnalysis: "Annual trends show peak incident reporting during semester periods (March-May and September-November) with notable decreases during semester breaks. Crime patterns indicate theft (35%) and vandalism (22%) as primary concerns. Facility issues predominantly involve electrical (38%) and plumbing (28%) systems. Average resolution time improved from 3.2 days to 2.7 days, demonstrating enhanced response efficiency.",
      riskAssessment: {
        level: "MEDIUM",
        factors: [
          "Aging campus infrastructure requiring systematic upgrades",
          "Seasonal variation in crime incidents",
          "Resource constraints during peak periods",
          "Growing student population impacting facility capacity",
        ],
      },
      recommendations: [
        "Develop 5-year infrastructure modernization plan",
        "Expand security team capacity by 20%",
        "Implement smart surveillance technology in high-risk areas",
        "Establish dedicated rapid response team for emergencies",
        "Enhance student safety education programs",
        "Create predictive analytics system for incident prevention",
        "Strengthen collaboration with local law enforcement",
      ],
      topLocations: [
        { location: "PTAR Library", count: 32 },
        { location: "Block A", count: 28 },
        { location: "Cafeteria", count: 24 },
        { location: "Hostel Block 1", count: 22 },
        { location: "Parking Lot A", count: 18 },
      ],
      conclusion: "Overall campus safety performance in 2023 demonstrates positive progress with declining crime rates and improved response times. Continued investment in infrastructure, technology, and human resources will be critical for maintaining and enhancing campus safety standards in 2024.",
    },
  },
  {
    generateId: "gen-rep-9",
    generatedBy: "staff-1",
    title: "Q4 2023 Facility Performance Review",
    summary: "Quarterly review of facility maintenance performance and service delivery metrics.",
    dateRangeStart: "2023-10-01T00:00:00Z",
    dateRangeEnd: "2023-12-31T23:59:59Z",
    reportCategory: "FACILITY",
    reportDataType: "SUMMARY",
    requestedAt: "2024-01-08T14:00:00Z",
    reportData: {
      totalReports: 56,
      pendingReports: 6,
      resolvedReports: 47,
      inProgressReports: 3,
      crimeReports: 0,
      facilityReports: 56,
      keyStatistics: {
        totalIncidents: 56,
        byStatus: {
          pending: 6,
          inProgress: 3,
          resolved: 47,
          rejected: 0,
        },
      },
      executiveSummary: "Q4 2023 facility performance shows 56 maintenance requests with 84% resolution rate. Average response time of 2.3 days slightly exceeds target but remains within acceptable parameters. Electrical and HVAC systems required increased attention during the quarter.",
      detailedAnalysis: "Quarter-end analysis reveals concentration of issues in older campus buildings. Electrical problems accounted for 35% of reports, while HVAC issues increased significantly due to seasonal temperature variations. Preventive maintenance programs showed positive impact with reduced emergency repairs.",
      topLocations: [
        { location: "Block A", count: 12 },
        { location: "Block C", count: 11 },
        { location: "Hostel Block 1", count: 9 },
        { location: "Library", count: 8 },
        { location: "Sports Complex", count: 7 },
      ],
      riskAssessment: {
        level: "LOW",
        factors: [
          "Aging HVAC systems requiring attention",
          "Seasonal weather impact on electrical systems",
          "Preventive maintenance showing positive results",
        ],
      },
      recommendations: [
        "Continue preventive maintenance programs",
        "Schedule HVAC system upgrades for older buildings",
        "Implement quarterly facility audits",
        "Maintain current staffing levels during peak periods",
      ],
      conclusion: "Q4 facility performance demonstrates effective maintenance operations. Continued focus on preventive measures and systematic upgrades will ensure sustained service quality.",
    },
  },
  {
    generateId: "gen-rep-10",
    generatedBy: "staff-1",
    title: "Student Safety Concerns Analysis - Fall 2023",
    summary: "Analysis of safety concerns raised by students during the fall semester.",
    dateRangeStart: "2023-09-01T00:00:00Z",
    dateRangeEnd: "2023-12-15T23:59:59Z",
    reportCategory: "CRIME",
    reportDataType: "SUMMARY",
    requestedAt: "2023-12-18T10:30:00Z",
    reportData: {
      totalReports: 38,
      pendingReports: 5,
      resolvedReports: 30,
      inProgressReports: 3,
      crimeReports: 38,
      facilityReports: 0,
      keyStatistics: {
        totalIncidents: 38,
        byStatus: {
          pending: 5,
          inProgress: 3,
          resolved: 30,
          rejected: 0,
        },
      },
      executiveSummary: "Fall 2023 semester recorded 38 student-reported safety concerns with 79% resolution rate. Primary concerns centered around evening security, poorly lit areas, and theft prevention. Student engagement in reporting remained high throughout the semester.",
      detailedAnalysis: "Student concerns predominantly focused on theft (45%) and inadequate security presence (32%) during evening hours. Library, parking areas, and hostel blocks received most attention. Response times averaged 1.8 hours for urgent concerns, meeting service targets.",
      topLocations: [
        { location: "PTAR Library", count: 10 },
        { location: "Parking Lot A", count: 8 },
        { location: "Hostel Block 1", count: 7 },
        { location: "Cafeteria", count: 6 },
        { location: "Sports Complex", count: 7 },
      ],
      riskAssessment: {
        level: "MEDIUM",
        factors: [
          "Limited evening security coverage",
          "Inadequate lighting in parking and outdoor areas",
          "Student concerns about personal property security",
          "Peak evening activity requires enhanced presence",
        ],
      },
      recommendations: [
        "Expand security patrol coverage during evening hours (6 PM - 11 PM)",
        "Upgrade lighting systems in parking lots and pathways",
        "Install additional emergency call stations",
        "Launch student safety awareness campaign",
        "Implement escort service during late hours",
      ],
      conclusion: "Student safety concerns reflect genuine campus needs requiring prompt attention. Addressing evening security and lighting issues will significantly enhance student confidence and campus safety perception.",
    },
  },
];