import { AnyReport, ReportAssignment, Student, Staff, Announcement, GeneratedReport, UiTMAuxiliaryPolice, NationalEmergencyService } from "@/lib/types";

// Mock Users
export const MOCK_STUDENTS: Student[] = [
  {
    id: "user-1",
    email: "student@uitm.edu.my",
    name: "Ahmad Ali",
    contactNumber: "012-3456789",
    role: "STUDENT",
    studentId: "2023123456",
    program: "CS240",
    semester: 4,
    yearOfStudy: 2,
  },
];

export const MOCK_STAFF: Staff[] = [
  {
    id: "staff-1",
    email: "officer@uitm.edu.my",
    name: "Officer Abu",
    contactNumber: "013-9876543",
    role: "STAFF",
    staffId: "S12345",
    department: "Security",
    position: "Patrol Officer",
  },
];

// Mock Reports
export const MOCK_REPORTS: AnyReport[] = [
  {
    id: "rep-2",
    type: "CRIME",
    title: "Cyberbullying on Twitter",
    description: "I have been receiving harassing messages and threats from an anonymous account on Twitter.",
    location: "Online (Twitter)",
    status: "PENDING",
    submittedBy: "user-1",
    submittedAt: "2023-10-26T09:15:00Z",
    updatedAt: "2023-10-26T09:15:00Z",
    crimeCategory: "SOCIAL MEDIA BULLY",
    suspectDescription: "Twitter handle @anon_bully_123",
    evidenceDetails: "Screenshots of tweets and DMs attached."
  },
  {
    id: "rep-3",
    type: "CRIME",
    title: "Instagram Impersonation",
    description: "Someone created a fake Instagram profile using my photos and name to scam my friends.",
    location: "Online (Instagram)",
    status: "IN_PROGRESS",
    submittedBy: "user-1",
    submittedAt: "2023-10-27T14:20:00Z",
    updatedAt: "2023-10-28T10:00:00Z",
    crimeCategory: "ONLINE DEFAMATION",
    suspectDescription: "Unknown",
    victimInvolved: "Myself and 3 friends who were scammed"
  },
  {
    id: "rep-4",
    type: "CRIME",
    title: "Threatening Emails",
    description: "Received an email demanding money with threats to leak personal information.",
    location: "Online (Email)",
    status: "RESOLVED",
    submittedBy: "user-1",
    submittedAt: "2023-10-20T11:00:00Z",
    updatedAt: "2023-10-25T16:30:00Z",
    crimeCategory: "ONLINE THREAT",
    suspectDescription: "Email address: hacker@darkweb.mail",
    evidenceDetails: "Forwarded email headers and content."
  },
  {
    id: "rep-5",
    type: "CRIME",
    title: "WhatsApp Harassment",
    description: "Ex-partner is constantly sending abusive messages and calling from different numbers.",
    location: "Online (WhatsApp)",
    status: "PENDING",
    submittedBy: "user-1",
    submittedAt: "2023-10-28T08:45:00Z",
    updatedAt: "2023-10-28T08:45:00Z",
    crimeCategory: "HARASSMENT",
    suspectDescription: "Known individual",
    injuryLevel: "Psychological distress"
  },
  {
    id: "rep-6",
    type: "CRIME",
    title: "Phishing Attempt via SMS",
    description: "Received an SMS claiming to be from the bank asking for login details.",
    location: "Online (SMS)",
    status: "REJECTED",
    submittedBy: "user-1",
    submittedAt: "2023-10-29T13:10:00Z",
    updatedAt: "2023-10-30T09:20:00Z",
    crimeCategory: "OTHER",
    suspectDescription: "Sender ID: 68899",
    evidenceDetails: "Screenshot of SMS"
  },
  {
    id: "rep-7",
    type: "CRIME",
    title: "TikTok Cyberstalking",
    description: "A user is stitching all my videos with hateful comments and encouraging others to harass me.",
    location: "Online (TikTok)",
    status: "IN_PROGRESS",
    submittedBy: "user-1",
    submittedAt: "2023-10-30T15:40:00Z",
    updatedAt: "2023-10-31T11:15:00Z",
    crimeCategory: "SOCIAL MEDIA BULLY",
    suspectDescription: "TikTok user @hater_gonna_hate",
    evidenceDetails: "Video links and comment screenshots"
  },
  {
    id: "rep-8",
    type: "CRIME",
    title: "Doxxing on Forum",
    description: "My home address and phone number were posted on a student forum without my consent.",
    location: "Online (Student Forum)",
    status: "RESOLVED",
    submittedBy: "user-1",
    submittedAt: "2023-10-22T19:30:00Z",
    updatedAt: "2023-10-24T14:00:00Z",
    crimeCategory: "ONLINE DEFAMATION",
    suspectDescription: "User 'AnonStudent22'",
    victimInvolved: "Myself"
  },
  {
    id: "rep-9",
    type: "CRIME",
    title: "Sextortion Attempt",
    description: "Someone is threatening to release private photos unless I pay them.",
    location: "Online (Telegram)",
    status: "PENDING",
    submittedBy: "user-1",
    submittedAt: "2023-11-01T22:15:00Z",
    updatedAt: "2023-11-01T22:15:00Z",
    crimeCategory: "ONLINE THREAT",
    suspectDescription: "Telegram user ID 998877",
    evidenceDetails: "Chat logs"
  },
  {
    id: "rep-10",
    type: "CRIME",
    title: "Discord Server Raid",
    description: "A group of users joined our study group server and spammed inappropriate content.",
    location: "Online (Discord)",
    status: "RESOLVED",
    submittedBy: "user-1",
    submittedAt: "2023-10-15T16:00:00Z",
    updatedAt: "2023-10-16T10:00:00Z",
    crimeCategory: "HARASSMENT",
    suspectDescription: "Multiple users",
    evidenceDetails: "Server audit logs"
  },
  {
    id: "rep-11",
    type: "CRIME",
    title: "Fake Profile on Facebook",
    description: "A fake profile is using my name to post offensive political statements.",
    location: "Online (Facebook)",
    status: "IN_PROGRESS",
    submittedBy: "user-1",
    submittedAt: "2023-11-02T12:30:00Z",
    updatedAt: "2023-11-03T09:45:00Z",
    crimeCategory: "ONLINE DEFAMATION",
    suspectDescription: "Profile URL provided",
    victimInvolved: "Myself"
  },
];

export const MOCK_ASSIGNMENTS: ReportAssignment[] = [
  {
    id: "assign-1",
    reportId: "rep-2",
    assignedTo: "staff-1",
    assignedAt: "2023-10-25T09:00:00Z",
    status: "IN_PROGRESS",
    actionTaken: "Technician notified.",
  },
];

// Mock Announcements
export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Campus Safety Week 2023",
    message: "Join us for Campus Safety Week from November 1-7. Various activities and workshops on personal safety, crime prevention, and emergency preparedness will be conducted. All students and staff are encouraged to participate.",
    audience: "ALL",
    type: "EVENT",
    status: "PUBLISHED",
    priority: "HIGH",
    image_src: "/test.jpg",
    isPinned: true,
    startDate: "2023-11-01T00:00:00Z",
    endDate: "2023-11-07T23:59:59Z",
    createdAt: "2023-10-20T10:00:00Z",
    createdBy: "staff-1",
    createdByName: "Officer Abu",
    updatedAt: "2023-10-20T10:00:00Z",
  },
  {
    id: "ann-2",
    title: "Emergency Maintenance - Block C",
    message: "Emergency maintenance work will be carried out in Block C on October 30, 2023, from 9:00 AM to 5:00 PM. Water and electricity supply will be temporarily interrupted. Please plan accordingly.",
    audience: "ALL",
    type: "EMERGENCY",
    status: "PUBLISHED",
    priority: "HIGH",
    isPinned: false,
     image_src: "/test.jpg",
    startDate: "2025-12-01T00:00:00Z",
    endDate: "2025-12-30T23:59:59Z",
    createdAt: "2023-10-27T14:30:00Z",
    createdBy: "staff-1",
    createdByName: "Officer Abu",
    updatedAt: "2023-10-27T14:30:00Z",
  },
  {
    id: "ann-3",
    title: "New Crime Reporting Portal",
    message: "We are pleased to announce the launch of our new online crime reporting portal. Students and staff can now submit reports 24/7 through this platform. Visit the Crime Terminal section to get started.",
    audience: "ALL",
    type: "GENERAL",
    status: "PUBLISHED",
    priority: "MEDIUM",
    isPinned: false,
    startDate: "2025-12-01T00:00:00Z",
    endDate: "2025-12-30T23:59:59Z",
    createdAt: "2023-10-15T09:00:00Z",
    createdBy: "staff-1",
    createdByName: "Officer Abu",
    updatedAt: "2023-10-15T09:00:00Z",
  },
  {
    id: "ann-4",
    title: "Updated Emergency Contact Numbers",
    message: "Please note that the UiTM Auxiliary Police emergency contact numbers have been updated. The new hotline is 03-5544-2222. Please update your contact lists accordingly.",
    audience: "ALL",
    type: "GENERAL",
    status: "PUBLISHED",
    priority: "MEDIUM",
    isPinned: false,
    startDate: "2023-10-10T00:00:00Z",
    endDate: "2023-11-30T23:59:59Z",
    createdAt: "2023-10-10T11:00:00Z",
    createdBy: "staff-1",
    createdByName: "Officer Abu",
    updatedAt: "2023-10-10T11:00:00Z",
  },
  {
    id: "ann-5",
    title: "Staff Training: Report Management",
    message: "Mandatory training session for all staff members on the new report management system. Session will be held on November 5, 2023, at 2:00 PM in Meeting Room A.",
    audience: "STAFF",
    type: "EVENT",
    status: "PUBLISHED",
    priority: "HIGH",
    isPinned: false,
    startDate: "2023-10-25T00:00:00Z",
    endDate: "2023-11-05T23:59:59Z",
    createdAt: "2023-10-25T08:00:00Z",
    createdBy: "staff-1",
    createdByName: "Officer Abu",
    updatedAt: "2023-10-25T08:00:00Z",
  },
  {
    id: "ann-6",
    title: "Draft: Upcoming Security Policy Changes",
    message: "This is a draft announcement about upcoming changes to campus security policies. Will be published after review.",
    audience: "ALL",
    type: "GENERAL",
    status: "DRAFT",
    priority: "LOW",
    isPinned: false,
    startDate: "2023-11-15T00:00:00Z",
    endDate: "2023-12-31T23:59:59Z",
    createdAt: "2023-10-26T15:00:00Z",
    createdBy: "staff-1",
    createdByName: "Officer Abu",
    updatedAt: "2023-10-26T15:00:00Z",
  },
];

// Mock Generated Reports
export const MOCK_GENERATED_REPORTS: GeneratedReport[] = [
  {
    id: "gen-rep-1",
    generatedBy: "staff-1",
    title: "Monthly Crime Report - October 2023",
    summary: "Comprehensive analysis of crime reports submitted during October 2023. This report includes statistics on crime categories, resolution rates, and location hotspots.",
    dateRangeStart: "2023-10-01T00:00:00Z",
    dateRangeEnd: "2023-10-31T23:59:59Z",
    category: "CRIME",
    dataType: "DETAILED",
    requestedAt: "2023-11-01T09:00:00Z",
    data: {
      totalReports: 15,
      pendingReports: 3,
      resolvedReports: 10,
      inProgressReports: 2,
      crimeReports: 15,
      facilityReports: 0,
      reportsByCategory: {
        THEFT: 8,
        ASSAULT: 2,
        VANDALISM: 3,
        HARASSMENT: 1,
        OTHER: 1,
      },
      reportsByStatus: {
        PENDING: 3,
        IN_PROGRESS: 2,
        RESOLVED: 10,
        REJECTED: 0,
      },
      reportsByMonth: [
        { month: "Oct 2023", count: 15 },
      ],
      topLocations: [
        { location: "PTAR Library", count: 5 },
        { location: "Cafeteria", count: 3 },
        { location: "Parking Lot A", count: 2 },
        { location: "Block C", count: 2 },
        { location: "Sports Complex", count: 3 },
      ],
      averageResolutionTime: 3.5,
    },
  },
  {
    id: "gen-rep-2",
    generatedBy: "staff-1",
    title: "Facility Issues Summary - Q3 2023",
    summary: "Quarterly summary of facility issues reported across campus. Highlights maintenance priorities and recurring problems.",
    dateRangeStart: "2023-07-01T00:00:00Z",
    dateRangeEnd: "2023-09-30T23:59:59Z",
    category: "FACILITY",
    dataType: "SUMMARY",
    requestedAt: "2023-10-05T14:30:00Z",
    data: {
      totalReports: 42,
      pendingReports: 5,
      resolvedReports: 35,
      inProgressReports: 2,
      crimeReports: 0,
      facilityReports: 42,
      reportsByCategory: {
        ELECTRICAL: 15,
        PLUMBING: 12,
        FURNITURE: 8,
        INFRASTRUCTURE: 5,
        OTHER: 2,
      },
      reportsByStatus: {
        PENDING: 5,
        IN_PROGRESS: 2,
        RESOLVED: 35,
        REJECTED: 0,
      },
      reportsByMonth: [
        { month: "Jul 2023", count: 12 },
        { month: "Aug 2023", count: 18 },
        { month: "Sep 2023", count: 12 },
      ],
      topLocations: [
        { location: "Block A", count: 10 },
        { location: "Block C", count: 8 },
        { location: "Library", count: 7 },
        { location: "Cafeteria", count: 6 },
        { location: "Hostel Block 1", count: 11 },
      ],
      averageResolutionTime: 2.1,
    },
  },
  {
    id: "gen-rep-3",
    generatedBy: "staff-1",
    title: "Campus User Statistics - 2023",
    summary: "Annual overview of user statistics across the campus including students and staff activity.",
    dateRangeStart: "2023-01-01T00:00:00Z",
    dateRangeEnd: "2023-12-31T23:59:59Z",
    category: "USER",
    dataType: "DETAILED",
    requestedAt: "2023-11-15T10:00:00Z",
    data: {
      totalReports: 156,
      pendingReports: 12,
      resolvedReports: 130,
      inProgressReports: 14,
      crimeReports: 48,
      facilityReports: 108,
      reportsByCategory: {
        THEFT: 20,
        ASSAULT: 8,
        VANDALISM: 12,
        HARASSMENT: 5,
        OTHER: 3,
        ELECTRICAL: 35,
        PLUMBING: 28,
        FURNITURE: 25,
        INFRASTRUCTURE: 15,
      },
      reportsByStatus: {
        PENDING: 12,
        IN_PROGRESS: 14,
        RESOLVED: 130,
        REJECTED: 0,
      },
      reportsByMonth: [
        { month: "Jan", count: 10 },
        { month: "Feb", count: 12 },
        { month: "Mar", count: 15 },
        { month: "Apr", count: 11 },
        { month: "May", count: 8 },
        { month: "Jun", count: 5 },
        { month: "Jul", count: 12 },
        { month: "Aug", count: 18 },
        { month: "Sep", count: 14 },
        { month: "Oct", count: 22 },
        { month: "Nov", count: 17 },
        { month: "Dec", count: 12 },
      ],
      topLocations: [
        { location: "PTAR Library", count: 25 },
        { location: "Block A", count: 20 },
        { location: "Cafeteria", count: 18 },
        { location: "Hostel Block 1", count: 15 },
        { location: "Parking Lot A", count: 12 },
      ],
      averageResolutionTime: 2.8,
    },
  },
  {
    id: "gen-rep-4",
    generatedBy: "staff-1",
    title: "Weekly Crime Report - Nov Week 4",
    summary: "Weekly summary of crime incidents for the last week of November 2023.",
    dateRangeStart: "2023-11-20T00:00:00Z",
    dateRangeEnd: "2023-11-26T23:59:59Z",
    category: "CRIME",
    dataType: "SUMMARY",
    requestedAt: "2023-11-27T08:00:00Z",
    data: null,
  },
];
export const MOCK_NATIONAL_EMERGENCY_SERVICES: NationalEmergencyService[] = [
  {
    id: "1",
    name: "Ibu Pejabat Polis Kontinjen (IPK) Selangor",
    type: "Police",
    state: "Selangor",
    address: "Persiaran Masjid, Seksyen 9, 40000 Shah Alam, Selangor",
    phone: "03-5514 5222",
    
  },
  {
    id: "2",
    name: "Balai Bomba dan Penyelamat Shah Alam",
    type: "Fire",
    state: "Selangor",
    address: "Jalan Persiaran Perbandaran, Seksyen 14, 40000 Shah Alam, Selangor",
    phone: "03-5519 4444",
    
  },
  {
    id: "3",
    name: "Hospital Shah Alam",
    type: "Medical",
    state: "Selangor",
    address: "Jalan Persiaran Kayangan, Seksyen 7, 40000 Shah Alam, Selangor",
    phone: "03-5526 3000",
    
  },
  {
    id: "4",
    name: "Angkatan Pertahanan Awam (APM) Shah Alam",
    type: "Civil Defence",
    state: "Selangor",
    address: "Jalan Lompat Pagar 13/37, Seksyen 13, 40100 Shah Alam, Selangor",
    phone: "03-5510 6323",
    
  },
  {
    id: "5",
    name: "Ibu Pejabat Polis Kontinjen (IPK) Kuala Lumpur",
    type: "Police",
    state: "Kuala Lumpur",
    address: "Jalan Hang Tuah, 55200 Kuala Lumpur",
    phone: "03-2115 9999",
    
  },
  {
    id: "6",
    name: "Hospital Kuala Lumpur (HKL)",
    type: "Medical",
    state: "Kuala Lumpur",
    address: "Jalan Pahang, 50586 Kuala Lumpur",
    phone: "03-2615 5555",
    
  },
  {
    id: "7",
    name: "Balai Bomba dan Penyelamat Hang Tuah",
    type: "Fire",
    state: "Kuala Lumpur",
    address: "Jalan Hang Tuah, 55200 Kuala Lumpur",
    phone: "03-2148 4444",
    
  },
  {
    id: "8",
    name: "Ibu Pejabat Polis Kontinjen (IPK) Johor",
    type: "Police",
    state: "Johor",
    address: "Jalan Tebrau, 80990 Johor Bahru, Johor",
    phone: "07-221 2999",
    
  },
  {
    id: "9",
    name: "Hospital Sultanah Aminah",
    type: "Medical",
    state: "Johor",
    address: "Jalan Persiaran Abu Bakar Sultan, 80100 Johor Bahru, Johor",
    phone: "07-225 7000",
    
  },
  {
    id: "10",
    name: "Ibu Pejabat Polis Kontinjen (IPK) Pulau Pinang",
    type: "Police",
    state: "Penang",
    address: "Jalan Penang, 10000 George Town, Pulau Pinang",
    phone: "04-222 1522",
    
  },
];;

export const MOCK_UITM_AUXILIARY_POLICE: UiTMAuxiliaryPolice[] = [
  {
    id: "UITM-AP-1",
    name: "UiTM Shah Alam Auxiliary Police",
    campus: "Shah Alam",
    state: "Selangor",
    address: "Bangunan Keselamatan, UiTM Shah Alam, 40450 Shah Alam, Selangor",
    phone: "03-5544 2000",
    hotline: "03-5544 2222",
    email: "pb_uitm@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-2",
    name: "UiTM Puncak Alam Auxiliary Police",
    campus: "Puncak Alam",
    state: "Selangor",
    address: "Pejabat Polis Bantuan, UiTM Cawangan Selangor, Kampus Puncak Alam",
    phone: "03-3258 4000",
    hotline: "03-3258 4111",
    email: "pb_puncakalam@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-3",
    name: "UiTM Machang Auxiliary Police",
    campus: "Kelantan",
    state: "Kelantan",
    address: "Unit Polis Bantuan, UiTM Cawangan Kelantan, Kampus Machang, 18500 Machang, Kelantan",
    phone: "09-976 2000",
    hotline: "09-976 2222",
    email: "pb_kelantan@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-4",
    name: "UiTM Arau Auxiliary Police",
    campus: "Perlis",
    state: "Perlis",
    address: "Unit Polis Bantuan, UiTM Cawangan Perlis, Kampus Arau, 02600 Arau, Perlis",
    phone: "04-988 2000",
    hotline: "04-988 2222",
    email: "pb_perlis@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-5",
    name: "UiTM Merbok Auxiliary Police",
    campus: "Kedah",
    state: "Kedah",
    address: "Unit Polis Bantuan, UiTM Cawangan Kedah, Kampus Merbok, 08400 Merbok, Kedah",
    phone: "04-456 2000",
    hotline: "04-456 2222",
    email: "pb_kedah@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-6",
    name: "UiTM Permatang Pauh Auxiliary Police",
    campus: "Pulau Pinang",
    state: "Penang",
    address: "Unit Polis Bantuan, UiTM Cawangan Pulau Pinang, Kampus Permatang Pauh, 13500 Permatang Pauh, Pulau Pinang",
    phone: "04-382 2000",
    hotline: "04-382 2222",
    email: "pb_penang@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-7",
    name: "UiTM Seri Iskandar Auxiliary Police",
    campus: "Perak",
    state: "Perak",
    address: "Unit Polis Bantuan, UiTM Cawangan Perak, Kampus Seri Iskandar, 32610 Seri Iskandar, Perak",
    phone: "05-374 2000",
    hotline: "05-374 2222",
    email: "pb_perak@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-8",
    name: "UiTM Jengka Auxiliary Police",
    campus: "Pahang",
    state: "Pahang",
    address: "Unit Polis Bantuan, UiTM Cawangan Pahang, Kampus Jengka, 26400 Bandar Tun Abdul Razak Jengka, Pahang",
    phone: "09-460 2000",
    hotline: "09-460 2222",
    email: "pb_pahang@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-9",
    name: "UiTM Kuala Pilah Auxiliary Police",
    campus: "Negeri Sembilan",
    state: "Negeri Sembilan",
    address: "Unit Polis Bantuan, UiTM Cawangan Negeri Sembilan, Kampus Kuala Pilah, 72000 Kuala Pilah, Negeri Sembilan",
    phone: "06-483 2000",
    hotline: "06-483 2222",
    email: "pb_n9@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-10",
    name: "UiTM Alor Gajah Auxiliary Police",
    campus: "Melaka",
    state: "Melaka",
    address: "Unit Polis Bantuan, UiTM Cawangan Melaka, Kampus Alor Gajah, 78000 Alor Gajah, Melaka",
    phone: "06-558 2000",
    hotline: "06-558 2222",
    email: "pb_melaka@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-11",
    name: "UiTM Segamat Auxiliary Police",
    campus: "Segamat",
    state: "Johor",
    address: "Unit Polis Bantuan, UiTM Cawangan Johor, Kampus Segamat, 85000 Segamat, Johor",
    phone: "07-935 2000",
    hotline: "07-935 2222",
    email: "pb_johor@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-12",
    name: "UiTM Dungun Auxiliary Police",
    campus: "Terengganu",
    state: "Terengganu",
    address: "Unit Polis Bantuan, UiTM Cawangan Terengganu, Kampus Dungun, 23000 Dungun, Terengganu",
    phone: "09-840 0000",
    hotline: "09-840 2222",
    email: "pb_terengganu@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-13",
    name: "UiTM Kota Samarahan Auxiliary Police",
    campus: "Sarawak",
    state: "Sarawak",
    address: "Unit Polis Bantuan, UiTM Cawangan Sarawak, Kampus Samarahan, 94300 Kota Samarahan, Sarawak",
    phone: "082-677 200",
    hotline: "082-677 222",
    email: "pb_sarawak@uitm.edu.my",
    operatingHours: "24 Hours",
  },
  {
    id: "UITM-AP-14",
    name: "UiTM Kota Kinabalu Auxiliary Police",
    campus: "Sabah",
    state: "Sabah",
    address: "Unit Polis Bantuan, UiTM Cawangan Sabah, Kampus Kota Kinabalu, 88997 Kota Kinabalu, Sabah",
    phone: "088-325 000",
    hotline: "088-325 222",
    email: "pb_sabah@uitm.edu.my",
    operatingHours: "24 Hours",
  },
];
