/* eslint-disable @typescript-eslint/no-explicit-any */
import { BaseModel } from './base/BaseModel';

export interface GeneratedReportData {
  GENERATE_ID?: number;
  GENERATED_BY: number;
  TITLE: string;
  SUMMARY: string;
  DATE_RANGE_START: Date;
  DATE_RANGE_END: Date;
  REPORT_CATEGORY: string;
  REPORT_DATA_TYPE?: string;
  REPORT_DATA?: any;
  REQUESTED_AT?: Date;
  // Extended fields from JOINs
  GENERATED_BY_NAME?: string;
  GENERATED_BY_EMAIL?: string;
}

export class GeneratedReport extends BaseModel {
  constructor(data: GeneratedReportData) {
    super(data);
  }

  protected validate(): void {
    if (!this.getTitle()) {
      throw new Error('Report title is required');
    }
    if (!this.getSummary()) {
      throw new Error('Report summary is required');
    }
    if (!this.getGeneratedBy()) {
      throw new Error('Generated by account ID is required');
    }
  }

  // Getters
  getGenerateId(): number | undefined {
    return this.get<number>('GENERATE_ID');
  }

  getGeneratedBy(): number {
    return this.get<number>('GENERATED_BY');
  }

  getTitle(): string {
    return this.get<string>('TITLE');
  }

  getSummary(): string {
    return this.get<string>('SUMMARY');
  }

  getDateRangeStart(): Date {
    return this.get<Date>('DATE_RANGE_START');
  }

  getDateRangeEnd(): Date {
    return this.get<Date>('DATE_RANGE_END');
  }

  getReportCategory(): string {
    return this.get<string>('REPORT_CATEGORY');
  }

  getReportDataType(): string | undefined {
    return this.get<string>('REPORT_DATA_TYPE');
  }

  getReportData(): any {
    return this.get<any>('REPORT_DATA');
  }

  getRequestedAt(): Date | undefined {
    return this.get<Date>('REQUESTED_AT');
  }
}
