-- ============================================================================
-- CYBERCRIME PLATFORM DATABASE SCHEMA
-- Oracle Database 21c
-- ============================================================================

-- Drop existing objects idempotently (safe to rerun)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESOLUTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UITM_AUXILIARY_POLICE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FACILITY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRIME CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GENERATED_REPORT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REPORT_ASSIGNMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMERGENCY_INFO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REPORT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STAFF CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; /

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE account_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE student_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE staff_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE report_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE announcement_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE assignment_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE emergency_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE generate_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE resolution_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END; /

-- ============================================================================
-- SEQUENCES
-- ============================================================================

CREATE SEQUENCE account_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE student_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE staff_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE report_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE announcement_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE assignment_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE emergency_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE generate_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE resolution_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================================
-- TABLES
-- ============================================================================

-- 1. ACCOUNT TABLE (Base table for all users)
CREATE TABLE ACCOUNT (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    CONTACT_NUMBER VARCHAR2(20),
    ACCOUNT_TYPE VARCHAR2(20) DEFAULT 'STUDENT' CHECK (ACCOUNT_TYPE IN ('STUDENT', 'STAFF')),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_account_email UNIQUE (EMAIL)
);

-- 2. STUDENT TABLE (Extends ACCOUNT)
CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL UNIQUE,
    PROGRAM VARCHAR2(100),
    SEMESTER NUMBER,
    YEAR_OF_STUDY NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_student_account FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE
);

-- 3. STAFF TABLE (Extends ACCOUNT)
CREATE TABLE STAFF (
    STAFF_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL UNIQUE,
    ROLE VARCHAR2(20) DEFAULT 'STAFF' CHECK (ROLE IN ('STAFF', 'SUPERVISOR', 'ADMIN', 'SUPERADMIN')),
    DEPARTMENT VARCHAR2(100),
    POSITION VARCHAR2(100),
    SUPERVISOR_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_staff_account FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_staff_supervisor FOREIGN KEY (SUPERVISOR_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- 4. REPORT TABLE
CREATE TABLE REPORT (
    REPORT_ID NUMBER PRIMARY KEY,
    SUBMITTED_BY NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION CLOB NOT NULL,
    LOCATION VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED')),
    TYPE VARCHAR2(20) NOT NULL CHECK (TYPE IN ('CRIME', 'FACILITY')),
    ATTACHMENT_PATH VARCHAR2(500),
    SUBMITTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_report_submitter FOREIGN KEY (SUBMITTED_BY) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- 5. CRIME TABLE (1:1 with REPORT where TYPE='CRIME')
CREATE TABLE CRIME (
    REPORT_ID NUMBER PRIMARY KEY,
    CRIME_CATEGORY VARCHAR2(50) NOT NULL CHECK (CRIME_CATEGORY IN ('THEFT', 'ASSAULT', 'VANDALISM', 'HARASSMENT', 'OTHER')),
    SUSPECT_DESCRIPTION VARCHAR2(500),
    VICTIM_INVOLVED VARCHAR2(100),
    INJURY_LEVEL VARCHAR2(50),
    WEAPON_INVOLVED VARCHAR2(100),
    EVIDENCE_DETAILS CLOB,
    CONSTRAINT fk_crime_report FOREIGN KEY (REPORT_ID) REFERENCES REPORT(REPORT_ID) ON DELETE CASCADE
);

-- 6. FACILITY TABLE (1:1 with REPORT where TYPE='FACILITY')
CREATE TABLE FACILITY (
    REPORT_ID NUMBER PRIMARY KEY,
    FACILITY_TYPE VARCHAR2(50) NOT NULL CHECK (FACILITY_TYPE IN ('ELECTRICAL', 'PLUMBING', 'FURNITURE', 'INFRASTRUCTURE', 'OTHER')),
    SEVERITY_LEVEL VARCHAR2(20) NOT NULL CHECK (SEVERITY_LEVEL IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    AFFECTED_EQUIPMENT VARCHAR2(500),
    CONSTRAINT fk_facility_report FOREIGN KEY (REPORT_ID) REFERENCES REPORT(REPORT_ID) ON DELETE CASCADE
);

-- 7. REPORT_ASSIGNMENT TABLE
CREATE TABLE REPORT_ASSIGNMENT (
    ASSIGNMENT_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    REPORT_ID NUMBER NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTION_TAKEN VARCHAR2(500),
    ADDITIONAL_FEEDBACK CLOB,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_assignment_account FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_report FOREIGN KEY (REPORT_ID) REFERENCES REPORT(REPORT_ID) ON DELETE CASCADE
);

-- 8. EMERGENCY_INFO TABLE
CREATE TABLE EMERGENCY_INFO (
    EMERGENCY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200),
    CAMPUS VARCHAR2(200),
    ADDRESS VARCHAR2(500) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100),
    STATE VARCHAR2(50) NOT NULL,
    TYPE VARCHAR2(50) CHECK (TYPE IN ('Police', 'Fire', 'Medical', 'Civil Defence')),
    HOTLINE VARCHAR2(50),
    OPERATING_HOURS VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 9. UITM_AUXILIARY_POLICE TABLE (Extends EMERGENCY_INFO)
CREATE TABLE UITM_AUXILIARY_POLICE (
    EMERGENCY_ID NUMBER PRIMARY KEY,
    CAMPUS VARCHAR2(100) NOT NULL,
    OPERATING_HOURS VARCHAR2(100),
    CONSTRAINT fk_police_emergency FOREIGN KEY (EMERGENCY_ID) REFERENCES EMERGENCY_INFO(EMERGENCY_ID) ON DELETE CASCADE
);

-- 10. ANNOUNCEMENT TABLE
CREATE TABLE ANNOUNCEMENT (
    ANNOUNCEMENT_ID NUMBER PRIMARY KEY,
    CREATED_BY NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    MESSAGE CLOB NOT NULL,
    AUDIENCE VARCHAR2(20) DEFAULT 'ALL' CHECK (AUDIENCE IN ('ALL', 'STUDENTS', 'STAFF', 'ADMIN')),
    TYPE VARCHAR2(20) DEFAULT 'GENERAL' CHECK (TYPE IN ('GENERAL', 'EMERGENCY', 'EVENT')),
    PRIORITY VARCHAR2(20) DEFAULT 'MEDIUM' CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH')),
    STATUS VARCHAR2(20) DEFAULT 'PUBLISHED' CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    PHOTO_PATH VARCHAR2(500),
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT ck_announcement_dates CHECK (END_DATE IS NULL OR END_DATE >= START_DATE),
    CONSTRAINT fk_announcement_creator FOREIGN KEY (CREATED_BY) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- 11. GENERATED_REPORT TABLE
CREATE TABLE GENERATED_REPORT (
    GENERATE_ID NUMBER PRIMARY KEY,
    GENERATED_BY NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    SUMMARY CLOB,
    DATE_RANGE_START DATE NOT NULL,
    DATE_RANGE_END DATE NOT NULL,
    REPORT_CATEGORY VARCHAR2(50) NOT NULL CHECK (REPORT_CATEGORY IN ('CRIME', 'FACILITY', 'USER', 'ALL REPORTS')),
    REPORT_DATA_TYPE VARCHAR2(20) NOT NULL CHECK (REPORT_DATA_TYPE IN ('JSON', 'SUMMARY', 'DETAILED')),
    REPORT_DATA CLOB,
    REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT ck_generated_report_dates CHECK (DATE_RANGE_END >= DATE_RANGE_START),
    CONSTRAINT fk_generated_report_account FOREIGN KEY (GENERATED_BY) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- 12. RESOLUTION TABLE
CREATE TABLE RESOLUTION (
    RESOLUTION_ID NUMBER PRIMARY KEY,
    REPORT_ID NUMBER NOT NULL,
    RESOLVED_BY NUMBER NOT NULL,
    RESOLUTION_TYPE VARCHAR2(20) NOT NULL CHECK (RESOLUTION_TYPE IN ('RESOLVED', 'ESCALATED', 'DISMISSED', 'TRANSFERRED')),
    RESOLUTION_SUMMARY CLOB NOT NULL,
    EVIDENCE_PATH VARCHAR2(500),
    RESOLVED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_resolution_report FOREIGN KEY (REPORT_ID) REFERENCES REPORT(REPORT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_resolution_account FOREIGN KEY (RESOLVED_BY) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX idx_account_email ON ACCOUNT(EMAIL);
CREATE INDEX idx_account_type ON ACCOUNT(ACCOUNT_TYPE);
CREATE INDEX idx_student_account ON STUDENT(ACCOUNT_ID);
CREATE INDEX idx_staff_account ON STAFF(ACCOUNT_ID);
CREATE INDEX idx_staff_supervisor ON STAFF(SUPERVISOR_ID);
CREATE INDEX idx_report_submitted_by ON REPORT(SUBMITTED_BY);
CREATE INDEX idx_report_status ON REPORT(STATUS);
CREATE INDEX idx_report_type ON REPORT(TYPE);
CREATE INDEX idx_report_submitted_at ON REPORT(SUBMITTED_AT);
CREATE INDEX idx_assignment_account ON REPORT_ASSIGNMENT(ACCOUNT_ID);
CREATE INDEX idx_assignment_report ON REPORT_ASSIGNMENT(REPORT_ID);
CREATE INDEX idx_assignment_updated ON REPORT_ASSIGNMENT(UPDATED_AT);
CREATE INDEX idx_announcement_audience ON ANNOUNCEMENT(AUDIENCE);
CREATE INDEX idx_announcement_status ON ANNOUNCEMENT(STATUS);
CREATE INDEX idx_announcement_dates ON ANNOUNCEMENT(START_DATE, END_DATE);
CREATE INDEX idx_emergency_state ON EMERGENCY_INFO(STATE);
CREATE INDEX idx_emergency_type ON EMERGENCY_INFO(TYPE);

-- ============================================================================
-- TRIGGERS FOR AUTO-UPDATE TIstudent_bi
BEFORE INSERT ON STUDENT
FOR EACH ROW
BEGIN
    IF :NEW.STUDENT_ID IS NULL THEN
        SELECT student_seq.NEXTVAL INTO :NEW.STUDENT_ID FROM dual;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_student_bu
BEFORE UPDATE ON STUDENT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_staff_bi
BEFORE INSERT ON STAFF
FOR EACH ROW
BEGIN
    IF :NEW.STAFF_ID IS NULL THEN
        SELECT staff_seq.NEXTVAL INTO :NEW.STAFF_ID FROM dual;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_staff_bu
BEFORE UPDATE ON STAFF
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ============================================================================
-- TRIGGERS FOR AUTO-POPULATING IDS AND TIMESTAMPS
-- ============================================================================

CREATE OR REPLACE TRIGGER trg_account_bi
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
    IF :NEW.ACCOUNT_ID IS NULL THEN
        SELECT account_seq.NEXTVAL INTO :NEW.ACCOUNT_ID FROM dual;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_account_bu
BEFORE UPDATE ON ACCOUNT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_report_bi
BEFORE INSERT ON REPORT
FOR EACH ROW
BEGIN
    IF :NEW.REPORT_ID IS NULL THEN
        SELECT report_seq.NEXTVAL INTO :NEW.REPORT_ID FROM dual;
    END IF;
    IF :NEW.SUBMITTED_AT IS NULL THEN
        :NEW.SUBMITTED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_report_bu
BEFORE UPDATE ON REPORT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_announcement_bi
BEFORE INSERT ON ANNOUNCEMENT
FOR EACH ROW
BEGIN
    IF :NEW.ANNOUNCEMENT_ID IS NULL THEN
        SELECT announcement_seq.NEXTVAL INTO :NEW.ANNOUNCEMENT_ID FROM dual;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_announcement_bu
BEFORE UPDATE ON ANNOUNCEMENT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := TAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_emergency_bi
BEFORE INSERT ON EMERGENCY_INFO
FOR EACH ROW
BEGIN
    IF :NEW.EMERGENCY_ID IS NULL THEN
        SELECT emergency_info_seq.NEXTVAL INTO :NEW.EMERGENCY_ID FROM dual;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_emergency_bu
BEFORE UPDATE ON EMERGENCY_INFO
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_report_assignment_bi
BEFORE INSERT ON REPORT_ASSIGNMENT
FOR EACH ROW
BEGIN
    IF :NEW.ASSIGNMENT_ID IS NULL THEN
        SELECT report_assignment_seq.NEXTVAL INTO :NEW.ASSIGNMENT_ID FROM dual;
    END IF;
    IF :NEW.ASSIGNED_AT IS NULL THEN
        :NEW.ASSIGNED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_generated_report_bi
BEFORE INSERT ON GENERATED_REPORT
FOR EACH ROW
BEGIN
    IF :NEW.GENERATE_ID IS NULL THEN
        SELECT generated_report_seq.NEXTVAL INTO :NEW.GENERATE_ID FROM dual;
    END IF;
    IF :NEW.REQUESTED_AT IS NULL THEN
        :NEW.REQUESTED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_resolution_bi
BEFORE INSERT ON RESOLUTION
FOR EACH ROW
BEGIN
    IF :NEW.RESOLUTION_ID IS NULL THEN
        SELECT resolution_seq.NEXTVAL INTO :NEW.RESOLUTION_ID FROM dual;
    END IF;
    IF :NEW.RESOLVED_AT IS NULL THEN
        :NEW.RESOLVED_AT := SYSTIMESTAMP;
    END IF;
END;
/

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- List all tables
SELECT table_name FROM user_tables ORDER BY table_name;

-- List all sequences
SELECT sequence_name FROM user_sequences ORDER BY sequence_name;

-- List all triggers
SELECT trigger_name FROM user_triggers ORDER BY trigger_name;

-- List all indexes
SELECT index_name, table_name FROM user_indexes WHERE table_name IN (
    'ACCOUNT', 'STUDENT', 'STAFF', 'REPORT', 'CRIME', 'FACILITY',
    'REPORT_ASSIGNMENT', 'EMERGENCY_INFO', 'UITM_AUXILIARY_POLICE',
    'ANNOUNCEMENT', 'GENERATED_REPORT', 'RESOLUTION'
) ORDER BY table_name, index_name;
