/* eslint-disable @typescript-eslint/no-explicit-any */

"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ArrowLeft, FileText, Download, Sparkles, Calendar, Clock } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { GeneratedReportCategory, GeneratedReportDataType, GeneratedReport } from "@/lib/types";
import { aiService } from "@/lib/api/ai-service";
import { format } from "date-fns";
import { useAuth } from "@/lib/context/auth-provider";
import { generateMetadata } from "@/lib/seo";
export default function GenerateReportPage() {
  // Form state
  const [title, setTitle] = useState("");
  const [category, setCategory] = useState<GeneratedReportCategory>("ALL REPORTS");
  const [dataType, setDataType] = useState<GeneratedReportDataType>("SUMMARY");
  const [dateRangeStart, setDateRangeStart] = useState("");
  const [dateRangeEnd, setDateRangeEnd] = useState("");
  
  // Generation state
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState<GeneratedReport | null>(null);
  const [error, setError] = useState<string>("");
  

  const { claims } = useAuth();
  const AcconutID = claims?.ACCOUNT_ID || "staff-1";

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);
    setError("");
    setGeneratedReport(null);

    try {
      // Fetch reports with filters from API
      const params = new URLSearchParams();
      if (category !== "ALL REPORTS") {
        params.append('type', category);
      }
      params.append('start_date', dateRangeStart);
      params.append('end_date', dateRangeEnd);

      const response = await fetch(`/api/reports?${params.toString()}`);
      if (!response.ok) throw new Error('Failed to fetch filtered reports');
      const data = await response.json();
      const filteredReports = data.reports || data;

      // Prepare report data for AI
      const reportData = {
        totalReports: filteredReports.length,
        byStatus: {
          pending: filteredReports.filter((r: { STATUS: string; }) => r.STATUS === "PENDING").length,
          inProgress: filteredReports.filter((r: { STATUS: string; }) => r.STATUS === "IN_PROGRESS").length,
          resolved: filteredReports.filter((r: { STATUS: string; }) => r.STATUS === "RESOLVED").length,
          rejected: filteredReports.filter((r: { STATUS: string; }) => r.STATUS === "REJECTED").length,
        },
        reports: filteredReports.map((r: { TITLE: any; LOCATION: any; STATUS: any; SUBMITTED_AT: any; TYPE: any; }) => ({
          title: r.TITLE,
          location: r.LOCATION,
          status: r.STATUS,
          submittedAt: r.SUBMITTED_AT,
          type: r.TYPE,
        })),
      };

      // Build prompt for AI
      const prompt = aiService.buildReportPrompt({
        category,
        dataType,
        dateRangeStart,
        dateRangeEnd,
        reportData,
      });

      // Generate report using AI
      const aiResponse = await aiService.generateReportData({
        prompt,
        temperature: 0.7,
        maxTokens: 2000,
      });

      // Parse AI response
      let parsedData;
      try {
        parsedData = JSON.parse(aiResponse.content);
      } catch {
        // If AI doesn't return valid JSON, create structured response
        parsedData = {
          executiveSummary: aiResponse.content,
          keyStatistics: reportData,
          detailedAnalysis: "Analysis generated by AI",
          riskAssessment: {
            level: "MEDIUM",
            factors: ["Data analysis in progress"],
          },
          recommendations: ["Continue monitoring"],
          conclusion: "Report generated successfully",
        };
      }

      // Create generated report object
      const generatedReportData : GeneratedReport = {
        GENERATE_ID: `gen-${Date.now()}`,
        GENERATED_BY: AcconutID,
        TITLE: title,
        SUMMARY: parsedData.executiveSummary || "Report generated",
        DATE_RANGE_START: dateRangeStart,
        DATE_RANGE_END: dateRangeEnd,
        REPORT_CATEGORY: category,
        REPORT_DATA_TYPE: dataType,
        REPORT_DATA: parsedData,
        REQUESTED_AT: new Date().toISOString(),
      };

      // Save generated report to server
      try {
        const saveResponse = await fetch('/api/generated-reports', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            title,
            summary: parsedData.executiveSummary || "Report generated",
            date_range_start: dateRangeStart,
            date_range_end: dateRangeEnd,
            report_category: category,
            report_data_type: dataType,
            report_data: parsedData,
            generated_by: AcconutID,
          }),
        });

        if (saveResponse.ok) {
          const savedReport = await saveResponse.json();
          // Update with server-generated ID
          generatedReportData.GENERATE_ID = `gen-${savedReport.generate_id}`;
        } else {
          console.warn('Failed to save report to server, but showing generated report');
        }
      } catch (saveError) {
        console.error('Error saving report to server:', saveError);
        // Continue to show the report even if saving fails
      }

      setGeneratedReport(generatedReportData);
    } catch (err) {
      console.error("Report generation error:", err);
      setError(
        err instanceof Error 
          ? err.message 
          : "Failed to generate report. Make sure LM Studio is running on localhost:1234"
      );
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!generatedReport) return;

    const dataStr = JSON.stringify(generatedReport, null, 2);
    const dataBlob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `report-${generatedReport.GENERATE_ID}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  generateMetadata({
    title: "Generate AI Report - Cybercrime Reporting Platform",
    description: "Create AI-powered analytical reports for campus safety data on the Cybercrime Reporting Platform.",
    canonical: "/dashboard/reports/report-summary/generate",
  });

  return (
    <div className="space-y-6 max-w-7xl mx-auto w-full">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" asChild>
          <Link href="/dashboard/reports/report-summary">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Reports summary
          </Link>
        </Button>
      </div>

      <div>
        <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
          <FileText className="h-8 w-8" />
          Generate Report
        </h1>
        <p className="text-muted-foreground">
          Create AI-powered analytical reports for campus safety data
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Form Section */}
        <div className="lg:col-span-2 space-y-6">
          <form onSubmit={handleGenerate} className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Report Configuration</CardTitle>
                <CardDescription>
                  Configure the parameters for your analytical report
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="title">Report Title *</Label>
                  <Input
                    id="title"
                    placeholder="e.g., Monthly Crime Analysis - November 2024"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    required
                  />
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="category">Report Category *</Label>
                    <Select value={category} onValueChange={(value) => setCategory(value as GeneratedReportCategory)}>
                      <SelectTrigger id="category">
                        <SelectValue placeholder="Select category" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="ALL REPORTS">All Reports</SelectItem>
                        <SelectItem value="CRIME">Crime Reports</SelectItem>
                        <SelectItem value="FACILITY">Facility Reports</SelectItem>
                        <SelectItem value="USER">User Activity</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="dataType">Report Type *</Label>
                    <Select value={dataType} onValueChange={(value) => setDataType(value as GeneratedReportDataType)}>
                      <SelectTrigger id="dataType">
                        <SelectValue placeholder="Select type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="SUMMARY">Summary</SelectItem>
                        <SelectItem value="DETAILED">Detailed</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="dateRangeStart">Start Date *</Label>
                    <Input
                      id="dateRangeStart"
                      type="date"
                      value={dateRangeStart}
                      onChange={(e) => setDateRangeStart(e.target.value)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="dateRangeEnd">End Date *</Label>
                    <Input
                      id="dateRangeEnd"
                      type="date"
                      value={dateRangeEnd}
                      onChange={(e) => setDateRangeEnd(e.target.value)}
                      required
                    />
                  </div>
                </div>

                {error && (
                  <div className="rounded-lg bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-900 p-4">
                    <p className="text-sm text-red-800 dark:text-red-200">{error}</p>
                  </div>
                )}

                <Button type="submit" className="w-full" disabled={isGenerating}>
                  {isGenerating ? (
                    <>
                      <Clock className="h-4 w-4 mr-2 animate-spin" />
                      Generating Report...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4 mr-2" />
                      Generate with AI
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          </form>

          {/* Generated Report Display */}
          {generatedReport && (
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>Generated Report</CardTitle>
                    <CardDescription>
                      AI-powered analysis of {generatedReport.REPORT_CATEGORY.toLowerCase()} data
                    </CardDescription>
                  </div>
                  <Button variant="outline" size="sm" onClick={handleDownload}>
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Executive Summary */}
                <div className="space-y-2">
                  <h3 className="font-semibold text-lg">Executive Summary</h3>
                  <p className="text-sm text-muted-foreground">
                    {generatedReport.REPORT_DATA.executiveSummary || generatedReport.SUMMARY}
                  </p>
                </div>

                {/* Key Statistics */}
                {generatedReport.REPORT_DATA.keyStatistics && (
                  <div className="space-y-2">
                    <h3 className="font-semibold text-lg">Key Statistics</h3>
                    <div className="grid gap-4 md:grid-cols-2">
                      <div className="rounded-lg border p-4">
                        <p className="text-sm text-muted-foreground">Total Incidents</p>
                        <p className="text-2xl font-bold">
                          {generatedReport.REPORT_DATA.keyStatistics.totalIncidents || 
                           generatedReport.REPORT_DATA.keyStatistics.totalReports || 0}
                        </p>
                      </div>
                      {generatedReport.REPORT_DATA.keyStatistics.byStatus && (
                        <>
                          <div className="rounded-lg border p-4 bg-yellow-50 dark:bg-yellow-950">
                            <p className="text-sm text-muted-foreground">Pending</p>
                            <p className="text-2xl font-bold text-yellow-600">
                              {generatedReport.REPORT_DATA.keyStatistics.byStatus.pending}
                            </p>
                          </div>
                          <div className="rounded-lg border p-4 bg-blue-50 dark:bg-blue-950">
                            <p className="text-sm text-muted-foreground">In Progress</p>
                            <p className="text-2xl font-bold text-blue-600">
                              {generatedReport.REPORT_DATA.keyStatistics.byStatus.inProgress}
                            </p>
                          </div>
                          <div className="rounded-lg border p-4 bg-green-50 dark:bg-green-950">
                            <p className="text-sm text-muted-foreground">Resolved</p>
                            <p className="text-2xl font-bold text-green-600">
                              {generatedReport.REPORT_DATA.keyStatistics.byStatus.resolved}
                            </p>
                          </div>
                        </>
                      )}
                    </div>
                  </div>
                )}

                {/* Detailed Analysis */}
                {generatedReport.REPORT_DATA.detailedAnalysis && (
                  <div className="space-y-2">
                    <h3 className="font-semibold text-lg">Detailed Analysis</h3>
                    <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                      {generatedReport.REPORT_DATA.detailedAnalysis}
                    </p>
                  </div>
                )}

                {/* Risk Assessment */}
                {generatedReport.REPORT_DATA.riskAssessment && (
                  <div className="space-y-2">
                    <h3 className="font-semibold text-lg">Risk Assessment</h3>
                    <div className="rounded-lg border p-4">
                      <p className="text-sm text-muted-foreground mb-2">Risk Level</p>
                      <div className="flex items-center gap-2">
                        <span className={`px-3 py-1 rounded-full text-sm font-semibold ${
                          generatedReport.REPORT_DATA.riskAssessment.level === 'CRITICAL' ? 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' :
                          generatedReport.REPORT_DATA.riskAssessment.level === 'HIGH' ? 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200' :
                          generatedReport.REPORT_DATA.riskAssessment.level === 'MEDIUM' ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' :
                          'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200'
                        }`}>
                          {generatedReport.REPORT_DATA.riskAssessment.level}
                        </span>
                      </div>
                      {generatedReport.REPORT_DATA.riskAssessment.factors && (
                        <div className="mt-4">
                          <p className="text-sm text-muted-foreground mb-2">Key Factors:</p>
                          <ul className="list-disc list-inside space-y-1">
                            {generatedReport.REPORT_DATA.riskAssessment.factors.map((factor: string, index: number) => (
                              <li key={index} className="text-sm">{factor}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                )}

                {/* Recommendations */}
                {generatedReport.REPORT_DATA.recommendations && (
                  <div className="space-y-2">
                    <h3 className="font-semibold text-lg">Recommendations</h3>
                    <ul className="list-decimal list-inside space-y-2">
                      {generatedReport.REPORT_DATA.recommendations.map((rec: string, index: number) => (
                        <li key={index} className="text-sm text-muted-foreground">{rec}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Conclusion */}
                {generatedReport.REPORT_DATA.conclusion && (
                  <div className="space-y-2">
                    <h3 className="font-semibold text-lg">Conclusion</h3>
                    <p className="text-sm text-muted-foreground">
                      {generatedReport.REPORT_DATA.conclusion}
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>About AI Reports</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
              <div>
                <h4 className="font-semibold mb-2">How it works</h4>
                <p className="text-muted-foreground">
                  Our AI analyzes your selected data range and generates comprehensive insights,
                  trends, and recommendations.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Report Types</h4>
                <ul className="space-y-1 text-muted-foreground">
                  <li>• <strong>Summary:</strong> High-level overview</li>
                  <li>• <strong>Detailed:</strong> In-depth analysis</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Categories</h4>
                <ul className="space-y-1 text-muted-foreground">
                  <li>• <strong>Crime:</strong> Crime incident analysis</li>
                  <li>• <strong>Facility:</strong> Facility issue trends</li>
                  <li>• <strong>User:</strong> User activity patterns</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-900">
            <CardHeader>
              <CardTitle className="text-blue-900 dark:text-blue-100 text-sm">
                <Sparkles className="h-4 w-4 inline mr-2" />
                AI Info
              </CardTitle>
            </CardHeader>
            <CardContent className="text-xs text-blue-800 dark:text-blue-200 space-y-2">
              <p>AI Generated data is still in beta testing. to ensure smooth usage, please ensure:</p>
              <ul className="list-disc list-inside space-y-1 ml-2">
                <li>you have stable internet connection</li>
                <li>the system is online and active</li>
              </ul>
            </CardContent>
          </Card>

          {generatedReport && (
            <Card>
              <CardHeader>
                <CardTitle className="text-sm">Report Metadata</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-xs">
                <div>
                  <p className="text-muted-foreground">Generated</p>
                  <p className="font-mono">{format(new Date(generatedReport.REQUESTED_AT), "PPp")}</p>
                </div>
                <div>
                  <p className="text-muted-foreground">Report ID</p>
                  <p className="font-mono">{generatedReport.GENERATE_ID}</p>
                </div>
                <div>
                  <p className="text-muted-foreground">Period</p>
                  <p className="flex items-center gap-1">
                    <Calendar className="h-3 w-3" />
                    {format(new Date(generatedReport.DATE_RANGE_START), "PP")} - {format(new Date(generatedReport.DATE_RANGE_END), "PP")}
                  </p>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
