"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  BarChart3,
  ArrowLeft,
  Calendar,
  User,
  Clock,
  CheckCircle2,
  FileText,
  MapPin,
  TrendingUp,
  ShieldAlert,
  Wrench,
} from "lucide-react";
import Link from "next/link";
import { MOCK_GENERATED_REPORTS } from "@/lib/api/mock-data";
import { format } from "date-fns";
import { notFound } from "next/navigation";

export default function ReportDetailPage({ params }: { params: { id: string } }) {
  const report = MOCK_GENERATED_REPORTS.find((r) => r.id === params.id);

  if (!report) {
    notFound();
  }

  const getCategoryColor = (category: string) => {
    switch (category) {
      case "CRIME":
        return "bg-red-500/10 text-red-500 border-red-500/20";
      case "FACILITY":
        return "bg-orange-500/10 text-orange-500 border-orange-500/20";
      case "USER":
        return "bg-blue-500/10 text-blue-500 border-blue-500/20";
      default:
        return "bg-gray-500/10 text-gray-500 border-gray-500/20";
    }
  };

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case "CRIME":
        return <ShieldAlert className="h-5 w-5 text-red-500" />;
      case "FACILITY":
        return <Wrench className="h-5 w-5 text-orange-500" />;
      case "USER":
        return <User className="h-5 w-5 text-blue-500" />;
      default:
        return <FileText className="h-5 w-5" />;
    }
  };

  // Calculate percentages for progress bars
  const getPercentage = (value: number, total: number) => {
    if (total === 0) return 0;
    return Math.round((value / total) * 100);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" asChild>
          <Link href="/dashboard/system-report">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to System Reports
          </Link>
        </Button>
      </div>

      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            {getCategoryIcon(report.category)}
            <h1 className="text-3xl font-bold tracking-tight">{report.title}</h1>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <User className="h-4 w-4" />
            <span>Generated by Staff ID: {report.generatedBy}</span>
            <span>•</span>
            <Clock className="h-4 w-4" />
            <span>{format(new Date(report.requestedAt), "PPP")}</span>
          </div>
        </div>
      </div>

      {/* Status and Info Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Category</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <Badge className={getCategoryColor(report.category)} variant="outline">
              {report.category}
            </Badge>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Report Type</CardTitle>
            <BarChart3 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <Badge variant="outline">{report.dataType}</Badge>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Date Range</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-sm">
              {format(new Date(report.dateRangeStart), "MMM d")} -{" "}
              {format(new Date(report.dateRangeEnd), "MMM d, yyyy")}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Report Summary */}
      <Card>
        <CardHeader>
          <CardTitle>Report Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground">{report.summary}</p>
        </CardContent>
      </Card>

      {/* Report Data - Only show if data exists */}
      {report.data && (
        <>
          {/* Key Metrics */}
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Reports</CardTitle>
                <FileText className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{report.data.totalReports}</div>
                <p className="text-xs text-muted-foreground">In selected period</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Resolved</CardTitle>
                <CheckCircle2 className="h-4 w-4 text-green-500" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-green-500">
                  {report.data.resolvedReports}
                </div>
                <p className="text-xs text-muted-foreground">
                  {getPercentage(report.data.resolvedReports || 0, report.data.totalReports || 0)}%
                  resolution rate
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Pending</CardTitle>
                <Clock className="h-4 w-4 text-yellow-500" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-yellow-500">
                  {report.data.pendingReports}
                </div>
                <p className="text-xs text-muted-foreground">Awaiting action</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Avg. Resolution</CardTitle>
                <TrendingUp className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{report.data.averageResolutionTime} days</div>
                <p className="text-xs text-muted-foreground">Average time to resolve</p>
              </CardContent>
            </Card>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            {/* Reports by Status */}
            {report.data.reportsByStatus && (
              <Card>
                <CardHeader>
                  <CardTitle>Reports by Status</CardTitle>
                  <CardDescription>Distribution of reports by their current status</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  {Object.entries(report.data.reportsByStatus as Record<string, number>).map(([status, count]) => (
                    <div key={status} className="space-y-2">
                      <div className="flex items-center justify-between text-sm">
                        <span>{status.replace("_", " ")}</span>
                        <span className="font-medium">{count}</span>
                      </div>
                      <Progress
                        value={getPercentage(count, report.data?.totalReports || 0)}
                        className="h-2"
                      />
                    </div>
                  ))}
                </CardContent>
              </Card>
            )}

            {/* Reports by Category */}
            {report.data.reportsByCategory && (
              <Card>
                <CardHeader>
                  <CardTitle>Reports by Category</CardTitle>
                  <CardDescription>Breakdown of reports by type/category</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  {Object.entries(report.data.reportsByCategory as Record<string, number>).map(([category, count]) => (
                    <div key={category} className="space-y-2">
                      <div className="flex items-center justify-between text-sm">
                        <span>{category}</span>
                        <span className="font-medium">{count}</span>
                      </div>
                      <Progress
                        value={getPercentage(count, report.data?.totalReports || 0)}
                        className="h-2"
                      />
                    </div>
                  ))}
                </CardContent>
              </Card>
            )}
          </div>

          {/* Monthly Trend */}
          {report.data.reportsByMonth && report.data.reportsByMonth.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Monthly Trend</CardTitle>
                <CardDescription>Number of reports submitted per month</CardDescription>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Month</TableHead>
                      <TableHead className="text-right">Reports</TableHead>
                      <TableHead className="w-[50%]">Distribution</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {(report.data.reportsByMonth as Array<{ month: string; count: number }>).map((item) => {
                      const maxCount = Math.max(
                        ...(report.data!.reportsByMonth as Array<{ month: string; count: number }>).map((m) => m.count)
                      );
                      return (
                        <TableRow key={item.month}>
                          <TableCell className="font-medium">{item.month}</TableCell>
                          <TableCell className="text-right">{item.count}</TableCell>
                          <TableCell>
                            <Progress
                              value={getPercentage(item.count, maxCount)}
                              className="h-2"
                            />
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}

          {/* Top Locations */}
          {report.data.topLocations && report.data.topLocations.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MapPin className="h-5 w-5" />
                  Top Locations
                </CardTitle>
                <CardDescription>Most frequently reported locations</CardDescription>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Rank</TableHead>
                      <TableHead>Location</TableHead>
                      <TableHead className="text-right">Reports</TableHead>
                      <TableHead className="w-[40%]">Percentage</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {(report.data.topLocations as Array<{ location: string; count: number }>).map((item, index) => (
                      <TableRow key={item.location}>
                        <TableCell className="font-medium">#{index + 1}</TableCell>
                        <TableCell>{item.location}</TableCell>
                        <TableCell className="text-right">{item.count}</TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Progress
                              value={getPercentage(item.count, report.data?.totalReports || 0)}
                              className="h-2 flex-1"
                            />
                            <span className="text-sm text-muted-foreground w-12">
                              {getPercentage(item.count, report.data?.totalReports || 0)}%
                            </span>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}
        </>
      )}

      {/* Report Metadata */}
      <Card>
        <CardHeader>
          <CardTitle>Report Information</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <div className="text-sm font-medium text-muted-foreground">Report ID</div>
              <div className="text-sm font-mono">{report.id}</div>
            </div>
            <div className="space-y-2">
              <div className="text-sm font-medium text-muted-foreground">Generated By</div>
              <div className="text-sm">{report.generatedBy}</div>
            </div>
            <div className="space-y-2">
              <div className="text-sm font-medium text-muted-foreground">Requested At</div>
              <div className="text-sm">
                {format(new Date(report.requestedAt), "PPP 'at' p")}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}